### ISSUE TITLE
host header missing

### ISSUE THREAD

**Issue by nelson2005** [leafo/lapis#290] opened 2015-05-15 14:36 UTC
I get an internal error for some HTTP calls:

nterface1/openresty/luajit/share/lua/5.1/lapis/nginx.lua:104: attempt to index field http_host (a nil value)
...nterface1/openresty/luajit/share/lua/5.1/lapis/nginx.lua:104: in function fn
...nterface1/openresty/luajit/share/lua/5.1/lapis/nginx.lua:133: in function '__index'

It looks to me like the root problem is that there's an assumption that there's a 'Host:' header, which is required for HTTP/1.1 but not for HTTP/1.0... I vaguely remember something about the HTTP version in the docs, but can't find it right now

**Comment by thefosk** [comment] 2015-11-25 01:48
Duplicate of #305 ?

**Closed** 2016-03-25 19:10 UTC
