### ISSUE TITLE
Problem installing Lapis on Windows 10

### ISSUE THREAD

**Issue by darmie** [leafo/lapis#401] opened 2016-02-20 10:43 UTC
I couldn't install Lapis on windows 10 

```
Error: Failed installing dependency: https://luarocks.org/luacrypto-0.3.2-1.src.rock - Could not find header file for OPENSSL
  No file openssl/evp.h in c:/external/include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command.
Example: luarocks install luacrypto OPENSSL_DIR=/usr/local
```

**Comment by Tieske** [comment] 2016-02-21 22:24
Checkout http://www.thijsschreijer.nl/blog/?p=899 and from there you should be able to do the same for LuaCrypto

**Comment by darmie** [comment] 2016-02-22 20:33
@Tieske  Thanks for the blog, although I am having a problem 

```
Can't locate parent.pm in @INC (@INC contains: util . /usr/lib/perl5/5.8/msys /usr/lib/perl5/5.8 /usr/lib/perl5/site_perl/5.8/msys /usr/lib/perl5/site_perl/5.8 /usr/lib/perl5/vendor_perl/5.8/msys /usr/lib/perl5/vendor_perl/5.8) at util/dofile.pl line 38.
BEGIN failed--compilation aborted at util/dofile.pl line 38.

**Comment by darmie** [comment] 2016-02-22 20:59
I found a `parent.pm` file in a perl source I downloaded, `./configure mingw shared` ran successfully.  But when I run `make` it gives me this error

```
Can't open opensslv.h at ./util/mkdef.pl line 1548.
/bin/perl.exe ./util/mkrc.pl libcrypto-1_1.dll | windres --target=pe-i386 -o rc.o
Couldn't open include/openssl/opensslv.h: No such file or directory
c:\MinGW\bin\windres.exe: no resources
LD_LIBRARY_PATH=.: gcc -DDSO_WIN32 -DOPENSSL_THREADS -DOPENSSL_PIC -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="/usr/local/ssl" -DENGINESDIR="/usr/local/lib/engines" -D_WINDLL -D_MT -DL_ENDIAN -DWIN32_LEAN_AND_MEAN -DUNICODE -D_UNICODE -m32 -Wall -O3 -fomit-frame-pointer -DWHIRLPOOL_ASM -static-libgcc -shared -Wl,-Bsymbolic -Wl,--out-implib,libcrypto.dll.a crypto.def rc.o -o ./libcrypto-1_1.dll -Wl,--whole-archive ./libcrypto.a -Wl,--no-whole-archive -L. -lws2_32 -lgdi32 -lcrypt32
gcc.exe: error: rc.o: No such file or directory
make[4]: *** [link_shlib.mingw] Error 1
make[4]: Leaving directory `/c/openssl'
make[3]: *** [do_mingw-shared] Error 2
make[3]: Leaving directory `/c/openssl'
make[2]: *** [libcrypto.dll] Error 2
make[2]: Leaving directory `/c/openssl'
make[1]: *** [shared] Error 2
make[1]: Leaving directory `/c/openssl/crypto'
make: *** [build_crypto] Error 1

**Comment by Tieske** [comment] 2016-02-23 22:12
Sorry, couldn't reproduce.

strange though that perl appears incomplete. I used the graphical mingw installer, and just added the perl packages in there. That worked for me.

**Comment by darmie** [comment] 2016-02-23 22:16
I used the graphical MinGW installer too.

**Comment by leafo** [comment] 2016-03-25 18:43
Going to close this since it appears to be a dependency issue and not a lapis one. Feel free to re-open if there are any updates.

**Closed by leafo** 2016-03-25 18:43 UTC
