### ISSUE TITLE
How to use app:include in "lua mode"

### ISSUE THREAD

**Issue by CriztianiX** [leafo/lapis#329] opened 2015-09-03 20:32 UTC
Hey! When i use moonscript in my project, i use

```lua
@include "applications.users"
```

Now, i'am re-factoring an actual application written in "lua mode"
but i cannot use

```lua
local lapis = require("lapis")
local app = lapis.Application()
app:include("applications.users")
```

is it posible?

**Comment by starius** [comment] 2015-09-03 21:49
Duplicate of #255

**Closed** 2015-09-04 18:01 UTC
