### ISSUE TITLE
using arrays inside the HTML function

### ISSUE THREAD

**Issue by DarkWiiPlayer** [leafo/lapis#512] opened 2017-01-20 18:29 UTC
Out of curiosity, I tried if the following code works inside the html-builder function
```lua
    p {"testing", a{href="/route/to/web/page", "LINK"}, "testing some more"}
```
and, to my surprise, it did. Kind of. It created the a tag first, and the two strings just after that.
While I don't remember reading anywhere that his should actually work, and the "correct" way would be to pass a function to `p`, I do feel like this should at least throw some sort of error instead of just doing something completely weird. Either that or actually work, because (at least in lua) this is much simpler than passing an anonymous function, and, while not the functional way of doing things, I'd say this is the lua way of doing things. `</rant>` `<meta name="hashtag" content="pleasefixthis">`

EDIT:
I just had a quick look at the generated HTML code, and this is basically what it does:
```html
<a ...>LINK</a>
<p>testing...</p>
<!-- both text elements of the table are just combined into one, as they should if there was no a tag -->
```

**Comment by leafo** [comment] 2017-01-20 18:37
There are two approaches to builder syntax, having the builders return something, or having the builders write to a buffer and return nil.

Lapis uses the buffer approach, the reason why is because it enables to use language constructs like loops and if statements.

In your example, since each html builder function is writing to the buffer, the first one to get called is the first one to render. Since `a` is part of an argument to `p` it gets called first and is run.

You'll have to use the function syntax to work around this. The syntax isn't very pretty in Lua, since it was designed primarily for MoonScript.

**Comment by DarkWiiPlayer** [comment] 2017-01-20 19:22
this is somewhat offtopic, but I've been working with SVG generation lately, which is pretty much the same as generating xml, and the way I use loops is to create a new buffer "class", which is basically just the following factory function:
```lua
do
local meta = {__tostring = table.concat}
function newbuffer(tab)
    return setmetatable(tab or {insert=table.insert}, meta)
end
end

-- example
local buffer = newbuffer{"some ", "text "}
print(buffer) -- prints "some text"
```

**Comment by leafo** [comment] 2017-01-20 19:48
Lapis builder syntax should work for any xml, including svg.

Going to close this, open if you have any issues.

**Closed by leafo** 2017-01-20 19:48 UTC
